[transport.local.sender.nonblocking]
enable = true

[[transport.jms.listener]]
name = "myQueueConnectionFactory"
parameter.initial_naming_factory = "org.apache.activemq.jndi.ActiveMQInitialContextFactory"
parameter.provider_url = $env{JMS_PROVIDER_URL}
parameter.connection_factory_name = "QueueConnectionFactory"
parameter.connection_factory_type = "queue"
parameter.cache_level = "consumer"

[[transport.jms.listener]]
name = "default"
parameter.initial_naming_factory = "org.apache.activemq.jndi.ActiveMQInitialContextFactory"
parameter.provider_url = $env{JMS_PROVIDER_URL}
parameter.connection_factory_name = "QueueConnectionFactory"
parameter.connection_factory_type = "queue"