openapi: 3.0.1
info:
  title: mstoreMan_API
  description: API Definition of mstoreMan_API
  version: 1.0.0
servers:
- url: http://localhost:8290/queues
paths:
  /:
    get:
      responses:
        default:
          description: Default response
