openapi: 3.0.1
info:
  title: trigger-ms-copy
  description: API Definition of trigger-ms-copy
  version: 1.0.0
servers:
- url: http://localhost:8290/trigger-ms-copy
paths:
  /quote:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
